# Generated by Django 4.2.6 on 2023-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("trainer", "Trainer"), ("client", "Client")],
                default="client",
                max_length=255,
            ),
        ),
    ]
