# Generated by Django 4.2.6 on 2023-10-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="contentType",
            field=models.CharField(
                choices=[
                    ("article", "article"),
                    ("podcast", "podcast"),
                    ("blog", "blog"),
                ],
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.SlugField(max_length=250),
        ),
    ]
