# Generated by Django 4.2.6 on 2023-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("didactiek", "didactiek"),
                            ("begeleiding", "begeleiding"),
                            ("ondersteuning", "ondersteuning"),
                        ],
                        max_length=254,
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("answer", models.TextField()),
            ],
        ),
    ]
