# Generated by Django 4.2.6 on 2023-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0002_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
