# Generated by Django 4.2.6 on 2023-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0002_alter_content_contenttype_alter_content_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("client", "client")], default="client", max_length=255
            ),
        ),
    ]
