# Generated by Django 4.2.6 on 2023-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0003_content_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
