# Generated by Django 4.2.6 on 2023-10-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0004_alter_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
