# Generated by Django 4.2.6 on 2023-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0005_alter_content_description_alter_faq_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("Didactiek", "Didactiek"),
                    ("Training en Coaching", "Training en Coaching"),
                ],
                max_length=254,
            ),
        ),
    ]
