# Generated by Django 4.2.6 on 2023-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0006_alter_faq_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("Didactiek", "Didactiek"),
                    ("Pedagogiek", "Pedagogiek"),
                    ("Algemene vragen over lesgeven", "Algemene vragen over lesgeven"),
                    ("Training en Coaching", "Training en Coaching"),
                ],
                max_length=254,
            ),
        ),
    ]
